# Generated by Django 5.2 on 2025-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
